#!/bin/bash
#copy CGB files into directory
scp archive* emierdma@carbonate.uits.iu.edu:/N/slate/emierdma/GSF3587

#open archive
tar -xvf archive*

#unzip fastq.gz files
gunzip *.gz

#combine fastq files from both runs
cat GSF3587-N2_ctrl_rep1_S1_R1_001.fastq GSF3587-N2_ctrl_rep1_S1_R2_001.fastq >  GSF3587-N2_ctrl_rep1.fastq

#activate rnaseq environment
conda activate rnaseq

#unload perl
module unload perl

#Assign Variables
ASSEMBLY='ftp://ftp.wormbase.org/pub/wormbase/releases/WS275/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS275.genomic.fa.gz'
ANNOTATION='ftp://ftp.wormbase.org/pub/wormbase/releases/WS275/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS275.canonical_geneset.gtf.gz'

################################
## Generate STAR Genome Index ##
################################

# Make a directory to store the genome files.
mkdir -p genome/index

# Download and unpack the genome assembly.
curl $ASSEMBLY | gunzip > ./genome/assembly.fasta

# Download and unpack the genome annotation.
curl $ANNOTATION | gunzip > ./genome/annotation.gtf

# Create the STAR genome index.
# --genomeSAindexNbases 12 was recommended by software.
#STAR version 2.7.10b
STAR \
  --runThreadN 4 \
  --runMode genomeGenerate \
  --genomeDir genome/index \
  --genomeFastaFiles genome/assembly.fasta \
  --sjdbGTFfile genome/annotation.gtf \
  --genomeSAindexNbases 12

###########################
## Align Reads to Genome ##
###########################

# Create an output directory for aligned reads.
mkdir -p results/aligned

# Align the reads.
FASTQ=$GSF3587*

for FASTQ in ${FASTQ[@]}; do
  PREFIX=results/aligned/$(basename $FASTQ .fastq)_
  STAR \
    --runThreadN 8 \
    --outFilterMultimapNmax 1 \
    --outFilterScoreMinOverLread .66 \
    --outFilterMismatchNmax 10 \
    --outFilterMismatchNoverLmax .3 \
    --runMode alignReads \
    --genomeDir genome/index \
    --readFilesIn $FASTQ \
    --outFileNamePrefix $PREFIX \
    --outSAMattributes All \
    --outSAMtype BAM SortedByCoordinate
done

# Indexing the BAM files.
BAMS=($(find ./results/aligned -name "*\.bam"))

for BAM in ${BAMS[@]}; do
  samtools index $BAM
  done
  
#remove genome* and results* files
  
  ####################
## Count Features ##
####################

# Create an output directory for read counts.
mkdir -p results/counts

# Count reads.
BAMS=$(find ./results/aligned -name "*\.bam")

featureCounts \
  -a genome/annotation.gtf \
  -o results/counts/counts.tsv \
  -t gene \
  -g gene_id \
  --largestOverlap \
  --readExtension3 150 \
  --primary \
  -s 2 \
  -T 8 \
  ${BAMS}
done

# look at uniquely mapped reads %
head GSF2848....Log.final.out

# proceed to DESeq or SAILOR
